version: '3.8'

services:
  backend:
    container_name: backend-app
    build: ./app
    command: python ./main.py
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database


  database:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pets
    ports:
      - 5432:5432
