version: '3.8'

services:
  backend:
    build: ./app
    command: python ./main.py
    ports:
      - 3000:3000
    depends_on:
      - database


  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_SERVER=localhost
      - POSTGRES_DB=pets
    ports:
      - 5432:5432
