version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=pets
    ports:
      - 5432:5432