uvicorn:
  host: 0.0.0.0
  port: 3000
  log_level: info
  reload: false

db_connection:
  postgres_user: ${POSTGRES_USER}
  postgres_password: ${POSTGRES_PASSWORD}
  postgres_server: ${POSTGRES_SERVER}
  postgres_database: ${POSTGRES_DB}
  postgres_port: ${POSTGRES_PORT}

api_config:
  title: test_task
  description: API Documentation for test_task
  debug: False
  version: v1
  docs_url: /docs

logging:
  custom_log_level: false
  log_level: info
  file_path: logs